// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpydilkmtmgbunectxpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndweWRpbGttdG1nYnVuZWN0eHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Njc0MjUsImV4cCI6MjA2MzI0MzQyNX0.OXl2AHppGSFWSGypG_2_NZj7atD_gM_U2I7oAkpTB5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});